### ISSUE TITLE
提供计算粉丝增长的公式

### ISSUE THREAD

**Issue by leoqingliu** [banacola-team/mini-steemit#1]
请根据发帖数量和速度提供计算粉丝增长的公式 @bobdos

**Comment by bobdos** [comment]
* 游戏右上方显示玩家目前拥有的STEEM币数量；其数量增长快慢和玩家发post的数量、以及followers的增长快慢有关系；前提条件是至少发布一个帖子的情况下，才从0开始增长 [一篇帖子发完增加的 new_gain_steem = 100* (1 + 已经post的数量) + followers * 10]

* followers表示有多少个粉丝subscribe了自己；其数量的增长快慢和玩家点击“Type/Post”按钮的速度有关系；点击的快，增长的快；前提条件是至少发布一个帖子的情况下，才从0开始增长 [每10秒增加的 new_followers = (click_count_per_10_seconds / 10) * 100]

* following表示我subscribe多少个其他人；这个数量随机增长就好了，没什么依赖关系 [每10秒增加的 new_following = random(1,50)]

**Comment by leoqingliu** [comment]
Got it
