### ISSUE TITLE
游戏获取奖励界面上新增2个按钮 - 重新游戏/分享成果

### ISSUE THREAD

**Issue by bobdos** [banacola-team/mini-steemit#11]
游戏获取奖励界面上新增2个按钮 - 重新游戏/分享成功

* 重新游戏 (Play Again) - 点击后可以重新开始一局游戏
* 分享成果 (Share Reward) - 点击后发送一个帖子到steemit 

界面上提示一下用户，如果分享成果到steemit，则可以获得来自 @banacola 的点赞鼓励

**Comment by bobdos** [comment]
文字内容的本地化已经放在ui_zh-CN 和 ui_en-US json文件中

**Comment by leoqingliu** [comment]
提示出现的位置能否明确一下？

**Comment by bobdos** [comment]
@leoqingliu 

放在奖励图片和按钮之间，如下图所示

![image](https://user-images.githubusercontent.com/195643/42732274-c20e5b50-8861-11e8-826a-edf8eaa678e9.png)

**Comment by leoqingliu** [comment]
按钮及文字已经添加
