### ISSUE TITLE
中文的内容在加载显示的时候，如果是一整句话，会一下就把整句话给显示了

### ISSUE THREAD

**Issue by bobdos** [banacola-team/mini-steemit#19]
现象：
中文的内容在加载显示的时候，如果是一整句话，会一下就把整句话给显示了

期望：
中文的内容在加载显示的时候，如果是一整句话，也还是根据中文字逐个显示

分析原因：
中文和英文不一样的地方在于，单词不是以空格作为间隔判断的

**Comment by leoqingliu** [comment]
已修复

**Comment by bobdos** [comment]
verified and close it.
