### ISSUE TITLE
提供UI资源

### ISSUE THREAD

**Issue by leoqingliu** [banacola-team/mini-steemit#2]
请提供UI资源，包括mail图像，对话框，背景，奖励物品等

**Comment by bobdos** [comment]
- [ ] 背景图片
- [ ] email图片
- [ ] type按钮图片
- [ ] post按钮图片
- [ ] 对话框直接就只是白色就好了，不需要填色（参考steemit官方配色）
- [ ] 奖励物品

**Comment by bobdos** [comment]
done and close it.
