### ISSUE TITLE
在HTML5 build中，界面上的控件显示有错位

### ISSUE THREAD

**Issue by bobdos** [banacola-team/mini-steemit#20]
![image](https://user-images.githubusercontent.com/195643/42089153-6ae8ec8e-7bdf-11e8-9bb9-0d14c4ed17bd.png)

**Comment by leoqingliu** [comment]
老白，如何构建HTML5 版本？我想看一下

**Comment by bobdos** [comment]
@leoqingliu 

ZeroBrane 运行启动模拟器后，在模拟器的菜单中

File -> Build -> HTML5(beta)

![image](https://user-images.githubusercontent.com/195643/42732196-28442302-8860-11e8-9eb0-fa747b148ade.png)

**Comment by bobdos** [comment]
verified and close it.
