### ISSUE TITLE
游戏开始界面新增语言选择功能

### ISSUE THREAD

**Issue by bobdos** [banacola-team/mini-steemit#8]
功能需求：
* 游戏最开始界面提供简体中文和英文的语言选择
* 缺省为英文
* 主要是针对JSON文件进行语言区分
* posts.json 调整为2个单独的文件： posts_zh-CN.json 和 posts_en-US.json

示例代码段：
local supported_languages = {"en", "pt", "es", "de", "fr" }
local pref_language = system.getPreference("ui", "language")
local lang = "en"
for i = 1, #supported_languages do
    if pref_lang == supported_langauges[i] then
         lang = pref_lang
         break
    end
end
-- 
-- at this point, "lang" is either going to be "en" or one of the 
-- supported languages.
--

**Comment by leoqingliu** [comment]
目前增加了中文和英文的选择按钮

**Comment by bobdos** [comment]
verified and close it.
